var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    devtool : "source-map",
    entry: [
        "./src/js/app.js"
    ],
    output: {
        path: __dirname,
        filename: "[name].js"
    },
    resolve : {
        extensions : ['' , '.js']
    },
    module: {
        loaders: [
            {
                test: /\.js$/ ,
                loader : 'babel' ,
                exclude : /node_modules/ ,
                query : {
                    presets:['react']
                }
            },
            {
                test: /\.css$/,
                loader : 'style!css'
            },
            {
                test: /\.less$/,
                loader: "style!css!less"
            }
        ]
    },
    plugins : [
        //去重
        new webpack.optimize.DedupePlugin(),
        //热加载
        new webpack.HotModuleReplacementPlugin(),

        new HtmlWebpackPlugin({
            template: 'index.html', // Move the index.html file
            inject: true // inject all files that are generated by webpack, e.g. bundle.js, main.css with the correct HTML tags
        }),

    ],
};